urlpatterns = patterns(u'',
    (ur'^$', directory.views.homepage),
    (ur'^accounts/login/$', u'django.contrib.auth.views.login'),
    (ur'^admin/', include(admin.site.urls)),
    (ur'^ajax/check_login', directory.views.ajax_check_login),
    (ur'^ajax/delete', directory.views.ajax_delete),
    (ur'^ajax/download/(Email|Entity|Phone|Status|Tag|URL)',  directory.views.ajax_download_model),
    (ur'^ajax/login', directory.views.ajax_login_request),
    (ur'^ajax/new/Entity', directory.views.new_Entity),
    (ur'^ajax/profile/(\d+)', directory.views.ajax_profile),
    (ur'^ajax/saveimage/(\d+)', directory.views.saveimage),
    (ur'^ajax/save', directory.views.save),
    (ur'^ajax/search', directory.views.ajax_search),
    (ur'^(create/Entity)', directory.views.redirect),
    (ur'^(create/Location)', directory.views.redirect),
    (ur'^manage/Entity/?(\d*)', directory.views.modelform_Entity),
    (ur'^manage/Location/?(\d*)', directory.views.modelform_Location),
    (ur'^profile/images/(\d+)', directory.views.image),
    (ur'^profile/(new)$', directory.views.profile_new),
    (ur'^profile/(\d+)$', directory.views.profile_existing),
    )
